<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link
      href="/css/styles.css"
      rel="stylesheet"
 
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
      crossorigin="anonymous"
    />


    <script
      src="/js/main.js"
    ></script>

    <script
    type="text/javascript"
    src="https://code.jquery.com/jquery-1.11.3.min.js"
  ></script>


    <title>PHP Kontakt Formular</title>
  </head>