<div class="formular mt-4 ">
              <h3 class="mb-5">Kontaktformular</h3>
              <form class="row g-3">



              
              <h6>SMTP CONFIG</h6>
              <hr> 
              <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP server address</label>
                        <input type="text" class="form-control" placeholder="smtp.gmail.com" id="inputCity">
                    </div>


                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP port</label>
                        <input type="text" class="form-control" placeholder="465" id="inputCity">
                    </div>

                    
               
                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP username</label>
                        <input type="text" class="form-control" placeholder="you@gmail.com" id="inputCity">
                    </div>

                                   
                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP password</label>
                        <input type="text" class="form-control" placeholder="tecnoconcept123" id="inputCity">
                    </div>



                <h6 class="mt-5">MESSAGE</h6>
              <hr> 
              <div class="col-md-6">

                        <label for="inputEmail4" class="form-label">Name</label>
                        <input type="email" class="form-control" id="inputEmail4">
                    </div>


                    <div class="col-md-6">
                        <label for="inputPassword4" class="form-label">Nachname</label>
                        <input type="password" class="form-control" id="inputPassword4">
                    </div>





                    <div class="col-md-12">
                        <label for="inputEmail4" class="form-label">Email</label>
                        <input type="email" class="form-control" id="inputEmail4">
                    </div>


           
                    <div class="col-12">
                   
                
                        <label for="exampleFormControlTextarea1" class="form-label">Message</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

                    </div>


         








                    <div class="col-12">
                        <button type="submit" class="float-end btn btn-primary">Senden</button>
                    </div>


                    </form>





            </div>


