<div class="formular mt-4 ">
              <h3 class="mb-5">Kontaktformular</h3>
              <form onsubmit="submitData(this, event)" class="row g-3">
              
              <h6>SMTP CONFIG</h6>
              <hr> 
              <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP server address</label>
                        <input type="text" class="form-control" placeholder="smtp.gmail.com" id="smtpAdress" value="mx.tecno.de" required>
                    </div>


                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP port</label>
                        <input type="text" class="form-control" placeholder="465" id="smtpPort" value="25" required>
                    </div>

                    
               
                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP username</label>
                        <input type="text" class="form-control" placeholder="you@gmail.com" id="smtpUsername" value="temp-sergio@webmail.tecno24.de" required>
                    </div>

                                   
                    <div class="col-md-6">
                        <label for="inputCity" class="form-label">SMTP password</label>
                        <input type="password" class="form-control" placeholder="fh1YKg24grASMOD" id="smtpPassword" value="fh1YKg24grASMOD" required>
                    </div>



                                    <h6 class="mt-5">MESSAGE</h6>
                                <hr> 
                        <div class="col-md-6">

                                    <label for="inputEmail4" class="form-label">Name</label>
                                    <input type="text" class="form-control" id="name" required>
                                </div>


                                <div class="col-md-6">
                                    <label for="inputPassword4" class="form-label">Nachname</label>
                                    <input type="text" class="form-control" id="nachname" required>
                                </div>




              

                                <div class="col-md-6">
                                    <label for="inputEmail4" class="form-label">From:</label>
                                    <input type="email" class="form-control" id="email" value="temp-sergio@webmail.tecno24.de" required>
                                </div>



                                <div class="col-md-6">
                                    <label for="inputEmail4" class="form-label">To:</label>
                                    <input type="email" class="form-control" id="to_email" value="temp-sergio@webmail.tecno24.de" required>
                                </div>



                                <div class="col-md-12">
                                    <label for="inputEmail4" class="form-label">Subject</label>
                                    <input type="text" class="form-control" id="subject" placeholder="Subject" required>
                                </div>


                    
                                <div class="col-12">
                            
                            
                                    <label for="exampleFormControlTextarea1" class="form-label">Message</label>
                                    <textarea class="form-control" id="message" rows="3" required></textarea>

                                </div>


         

                        <div class="col-12">
                            <button type="submit" class="float-end btn btn-primary">Senden</button>
                        </div>

          

                    </form>

            </div>





 <!-- Modal -->
 <div
            class="modal fade"
            id="modalLoading"
            tabindex="-1"
            aria-labelledby="modalLoading"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered">
              <div
                class="modal-content border-0"
                style="background-color: transparent;"
              >
                <div class="d-flex justify-content-center">
                  <div class="spinner-border" role="status">
                    <span class="visually-hidden">Loading...</span>
                  </div>
                </div>
              </div>
            </div>
            <div
              class="modal-backdrop fade show"
              id="backdrop"
              style="display: none;"
            ></div>
          </div>




          <!-- Modal -->
          <div
            class="modal fade"
            id="successModal"
            tabindex="-1"
            aria-labelledby="exampleModalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">
                    Vielen Dank!
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-4" style="text-align: center;">
                      <img
                        style="width: 100px;"
                        src="/images/success-icon.png"
                        alt=""
                      />
                    </div>

                    <div class="col-8">
                      <p>Ihre Nachricht wurde versendet.</p>
                      <p>
                        Wir werden uns so bald wie möglich mit Ihnen in
                        Verbindung setzen.
                      </p>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                    onclick="window.location.href = '/'"
                  >
                    Schließen
                  </button>
                </div>
              </div>
            </div>
          </div>






             <!-- Modal -->
             <div
            class="modal fade"
            id="failModal"
            tabindex="-1"
            aria-labelledby="exampleModalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">
                    Fehlrgeschlagen
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <div class="row">
                    <div class="col-4" style="text-align: center;">
                      <img
                        style="width: 100px;"
                        src="/images/fail-icon.png"
                        alt=""
                      />
                    </div>

                    <div class="col-8">
                      <p>Ihre Nachricht konnte nicht versendet.</p>
                      <p>
                        Bitte versuchen Sie es später noch einmal.
                      </p>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                    onclick="window.location.href = '/'"
                  >
                    Schließen
                  </button>
                </div>
              </div>
            </div>
          </div>


