        
          <div class="col-auto" style="width: 300px;">
            <div
              class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark"
              style="width: 280px; height: 100%; position: fixed;"
            >
              <a
                href="/"
                class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"
              >
                <span class="fs-4">tecnoConcept Demo</span>
              </a>
              <hr />
              <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                  <a href="/index.php" class="nav-link text-white <?php echo $path ==
                  'index'
                      ? 'active'
                      : ''; ?>" aria-current="page">
                    Kontaktformular
                  </a>
                </li>

                <li>
                  <a href="/emails.php" class="nav-link text-white <?php echo $path ==
                  'emails'
                      ? 'active'
                      : ''; ?>">
                    Gespeicherte Emails
                  </a>
                </li>
              </ul>
              <hr />
            </div>
          </div>