<ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                  <a href="/index.php" class="nav-link text-white <?php echo $path ==
                  'index'
                      ? 'active'
                      : ''; ?>" aria-current="page">
                    Kontaktformular
                  </a>
                </li>

                <li>
                  <a href="/emails.php" class="nav-link text-white <?php echo $path ==
                  'emails'
                      ? 'active'
                      : ''; ?>">
                    Gespeicherte Emails
                  </a>
                </li>
              </ul>